export const USER_LOGIN_SUCCEEDED = "USER_LOGIN_SUCCEEDED";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const LOGOUT_SUCCEEDED = "LOGOUT_SUCCEEDED";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const EMAIL_VERIFIED = "EMAIL_VERIFIED";
